title: Windows Defender Exclusions Added
id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
status: stable
description: Detects the Setting of Windows Defender Exclusions
references:
    - https://twitter.com/_nullbind/status/1204923340810543109
author: Christian Burkard (Nextron Systems)
date: 2021/07/06
modified: 2022/12/06
tags:
    - attack.defense_evasion
    - attack.t1562.001
logsource:
    product: windows
    service: windefend
detection:
    windefend:
        Channel: Microsoft-Windows-Windows Defender/Operational
    selection:
        EventID: 5007 # The antimalware platform configuration changed.
        NewValue|contains: \Microsoft\Windows Defender\Exclusions
    condition: windefend and selection
falsepositives:
    - Administrator actions
level: medium
ruletype: Sigma
