
title: Sysmon Configuration Change
ruletype: Sigma
author: frack113
date: 2022/01/12
description: Detects a Sysmon configuration change, which could be the result of a
  legitimate reconfiguration or someone trying manipulate the configuration
detection:
  SELECTION_1:
    EventID: 16
  condition: SELECTION_1
falsepositives:
- Legitimate administrative action
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
level: medium
logsource:
  product: windows
  service: sysmon
references:
- https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon
status: experimental
tags:
- attack.defense_evasion
