title: New Application in AppCompat
ruletype: Sigma
author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
date: 2020/05/02
description: A General detection for a new application in AppCompat. This indicates
    an application executing for the first time on an endpoint.
detection:
    SELECTION_1:
        EventID: 4657
    SELECTION_2:
        OperationType:
        - Existing registry value modified
    SELECTION_3:
        Channel: Security
    SELECTION_4:
        EventType: Setvalue
    SELECTION_5:
        TargetObject: '*\AppCompatFlags\Compatibility Assistant\Store\\*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- This rule is to explore new applications on an endpoint. False positives depends
    on the organization.
- Newly setup system.
- Legitimate installation of new application.
id: 60936b49-fca0-4f32-993d-7415edcf9a5d
level: informational
logsource:
    category: registry_set
    product: windows
modified: 2022/06/26
references:
- https://github.com/OTRF/detection-hackathon-apt29/issues/1
- https://github.com/OTRF/ThreatHunter-Playbook/blob/2d4257f630f4c9770f78d0c1df059f891ffc3fec/docs/evals/apt29/detections/1.A.1_DFD6A782-9BDB-4550-AB6B-525E825B095E.md
status: test
tags:
- attack.execution
- attack.t1204.002

