title: Outlook Security Settings Updated - Registry
id: 8a91b3b9-6d62-e700-63e7-73170f5b0bbc
status: test
description: Detects changes to the registry values related to outlook security settings
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
    - https://docs.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
author: frack113
date: 2021/12/28
modified: 2023/08/17
tags:
    - attack.persistence
    - attack.t1137
    - sysmon
logsource:
    category: registry_set
    product: windows
detection:
    registry_set:
        EventID: 4657
        Channel: Security
    selection:
        ObjectName|contains|all:
            - \SOFTWARE\Microsoft\Office\
            - \Outlook\Security\
    condition: registry_set and selection
falsepositives:
    - Administrative activity
level: medium
ruletype: Sigma
