title: Windows Defender Firewall Has Been Reset To Its Default Configuration
ruletype: Sigma
author: frack113
date: 2022/02/19
description: Detects activity when Windows Defender Firewall has been reset to its
    default configuration
detection:
    SELECTION_1:
        Channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    SELECTION_2:
        EventID: 2032
    condition: (SELECTION_1 and SELECTION_2)
id: 04b60639-39c0-412a-9fbe-e82499c881a3
level: low
logsource:
    product: windows
    service: firewall-as
modified: 2023/01/17
references:
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
status: experimental

