title: Invoke-Obfuscation VAR+ Launcher - Security
id: dcf2db1f-f091-425b-a821-c05875b8925a
related:
    -   id: 8ca7004b-e620-4ecb-870e-86129b5b8e75
        type: derived
status: test
description: Detects Obfuscated use of Environment Variables to execute PowerShell
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
author: Jonathan Cheong, oscd.community
date: 2020/10/15
modified: 2022/11/29
tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    security:
        Channel: Security
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - cmd
            - '"set'
            - -f
        ServiceFileName|contains:
            - /c
            - /r
    condition: security and selection
falsepositives:
    - Unknown
level: high
ruletype: Sigma
