title: Invoke-Obfuscation Via Use Rundll32 - Security
ruletype: Sigma
author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use Rundll32 in Scripts
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4697
    SELECTION_3:
        ServiceFileName: '*&&*'
    SELECTION_4:
        ServiceFileName: '*rundll32*'
    SELECTION_5:
        ServiceFileName: '*shell32.dll*'
    SELECTION_6:
        ServiceFileName: '*shellexec_rundll*'
    SELECTION_7:
        ServiceFileName:
        - '*value*'
        - '*invoke*'
        - '*comspec*'
        - '*iex*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5
        and SELECTION_6 and SELECTION_7)
falsepositives:
- Unknown
id: cd0f7229-d16f-42de-8fe3-fba365fbcb3a
level: high
logsource:
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
    product: windows
    service: security
modified: 2022/11/29
references:
- https://github.com/SigmaHQ/sigma/issues/1009
related:
-   id: 641a4bfb-c017-44f7-800c-2aee0184ce9b
    type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001

