
title: Invoke-Obfuscation RUNDLL LAUNCHER
ruletype: Sigma
author: Timur Zinniatullin, oscd.community
date: 2020/10/18
description: Detects Obfuscated Powershell via RUNDLL LAUNCHER
detection:
  SELECTION_1:
    EventID: 4697
  SELECTION_2:
    ServiceFileName: '*rundll32.exe*'
  SELECTION_3:
    ServiceFileName: '*shell32.dll*'
  SELECTION_4:
    ServiceFileName: '*shellexec_rundll*'
  SELECTION_5:
    ServiceFileName: '*powershell*'
  condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- Unknown
id: f241cf1b-3a6b-4e1a-b4f9-133c00dd95ca
level: medium
logsource:
  product: windows
  service: security
modified: 2022/03/06
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 11b52f18-aaec-4d60-9143-5dd8cc4706b9
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
