title: Chafer Activity - Security
ruletype: Sigma
author: Florian Roth (Nextron Systems), Markus Neis, Jonhnathan Ribeiro, Daniil Yugoslavskiy,
    oscd.community
date: 2018/03/23
description: Detects Chafer activity attributed to OilRig as reported in Nyotron report
    in March 2018
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4698
    SELECTION_3:
        TaskName:
        - SC Scheduled Scan
        - UpdatMachine
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3)
falsepositives:
- Unknown
id: c0580559-a6bd-4ef6-b9b7-83703d98b561
level: critical
logsource:
    product: windows
    service: security
modified: 2022/11/27
references:
- https://nyotron.com/nyotron-discovers-next-generation-oilrig-attacks/
related:
-   id: 53ba33fd-3a50-4468-a5ef-c583635cfa92
    type: derived
status: test
tags:
- attack.persistence
- attack.g0049
- attack.t1053.005
- attack.s0111
- attack.t1543.003
- attack.defense_evasion
- attack.t1112
- attack.command_and_control
- attack.t1071.004

