title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION
ruletype: Sigma
author: Timur Zinniatullin, oscd.community
date: 2020/10/13
description: Detects Obfuscated Powershell via VAR++ LAUNCHER
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4697
    SELECTION_3:
        ServiceFileName: '*&&set*'
    SELECTION_4:
        ServiceFileName: '*cmd*'
    SELECTION_5:
        ServiceFileName: '*/c*'
    SELECTION_6:
        ServiceFileName: '*-f*'
    SELECTION_7:
        ServiceFileName:
        - '*{0}*'
        - '*{1}*'
        - '*{2}*'
        - '*{3}*'
        - '*{4}*'
        - '*{5}*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5
        and SELECTION_6 and SELECTION_7)
falsepositives:
- Unknown
id: 4c54ba8f-73d2-4d40-8890-d9cf1dca3d30
level: high
logsource:
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
    product: windows
    service: security
modified: 2022/11/17
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
-   id: 14bcba49-a428-42d9-b943-e2ce0f0f7ae6
    type: derived
status: test
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001

