
title: Invoke-Obfuscation Via Use MSHTA
ruletype: Sigma
author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use MSHTA in Scripts
detection:
  SELECTION_1:
    Channel: Security
  SELECTION_2:
    EventID: 4697
  SELECTION_3:
    ServiceFileName: '*mshta*'
  SELECTION_4:
    ServiceFileName: '*vbscript:createobject*'
  SELECTION_5:
    ServiceFileName: '*.run*'
  SELECTION_6:
    ServiceFileName: '*window.close*'
  condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5
    and SELECTION_6)
falsepositives:
- Unknown
id: 9b8d9203-4e0f-4cd9-bb06-4cc4ea6d0e9a
level: high
logsource:
  product: windows
  service: security
modified: 2022/02/03
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 7e9c7999-0f9b-4d4a-a6ed-af6d553d4af4
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
