
title: ADCS Certificate Template Configuration Vulnerability
ruletype: Sigma
author: Orlinum , BlueDefenZer
date: 2021/11/17
description: Detects certificate creation with template allowing risk permission subject
detection:
  SELECTION_1:
    Channel: Security
  SELECTION_2:
    EventID: 4898
  SELECTION_3:
    TemplateContent: '*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*'
  SELECTION_4:
    EventID: 4899
  SELECTION_5:
    NewTemplateContent: '*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*'
  condition: (SELECTION_1 and ((SELECTION_2 and SELECTION_3) or (SELECTION_4 and SELECTION_5)))
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
id: 5ee3a654-372f-11ec-8d3d-0242ac130003
level: low
logsource:
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be comming if template contain specific flag.
  product: windows
  service: security
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
status: experimental
tags:
- attack.privilege_escalation
- attack.credential_access
