title: ADCS Certificate Template Configuration Vulnerability
id: 5ee3a654-372f-11ec-8d3d-0242ac130003
status: test
description: Detects certificate creation with template allowing risk permission subject
references:
    - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
author: Orlinum , BlueDefenZer
date: 2021/11/17
modified: 2022/12/25
tags:
    - attack.privilege_escalation
    - attack.credential_access
logsource:
    product: windows
    service: security
    definition: Certificate services loaded a template would trigger event ID 4898 and certificate Services template was updated would trigger event ID 4899. A risk permission seems to be coming if template contain specific flag.
detection:
    security:
        Channel: Security
    selection1:
        EventID: 4898
        TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    selection2:
        EventID: 4899
        NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    condition: security and (selection1 or selection2)
falsepositives:
    - Administrator activity
    - Proxy SSL certificate with subject modification
    - Smart card enrollement
level: low
ruletype: Sigma
