title: Invoke-Obfuscation Via Stdin - Security
ruletype: Sigma
author: Nikita Nazarov, oscd.community
date: 2020/10/12
description: Detects Obfuscated Powershell via Stdin in Scripts
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4697
    SELECTION_3:
        ServiceFileName: '*set*'
    SELECTION_4:
        ServiceFileName: '*&&*'
    SELECTION_5:
        ServiceFileName:
        - '*environment*'
        - '*invoke*'
        - '*${input)*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- Unknown
id: 80b708f3-d034-40e4-a6c8-d23b7a7db3d1
level: high
logsource:
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
    product: windows
    service: security
modified: 2022/11/29
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
-   id: 487c7524-f892-4054-b263-8a0ace63fc25
    type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001

