title: UAC Bypass Using MSConfig Token Modification - Process
id: ad92e3f9-7eb6-460e-96b1-582b0ccbb980
status: test
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
references:
    - https://github.com/hfiref0x/UACME
author: Christian Burkard (Nextron Systems)
date: 2021/08/30
modified: 2022/10/09
tags:
    - attack.defense_evasion
    - attack.privilege_escalation
    - attack.t1548.002
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
    selection:
        IntegrityLevel:
            - High
            - System
        ParentImage|endswith: \AppData\Local\Temp\pkgmgr.exe
        CommandLine: '"C:\Windows\system32\msconfig.exe" -5'
    condition: process_creation and selection
falsepositives:
    - Unknown
level: high
ruletype: Sigma
