title: Arbitrary File Download Via ConfigSecurityPolicy.EXE
id: 4ef877bf-80c3-e2b3-56f8-8d82726854b7
related:
    - id: 1f0f6176-6482-4027-b151-00071af39d7e
      type: derived
status: test
description: |
    Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of Windows Defender used to manage settings in Windows Defender.
    Users can configure different pilot collections for each of the co-management workloads.
    It can be abused by attackers in order to upload or download files.
references:
    - https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
author: frack113
date: 2021-11-26
modified: 2022-05-16
tags:
    - attack.exfiltration
    - attack.t1567
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_img:
        - CommandLine|contains: ConfigSecurityPolicy.exe
        - Image|endswith: \ConfigSecurityPolicy.exe
        - OriginalFileName: ConfigSecurityPolicy.exe
    selection_url:
        CommandLine|contains:
            - ftp://
            - http://
            - https://
    condition: process_creation and (all of selection_*)
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
