title: Application Removed Via Wmic.EXE
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
related:
    - id: 847d5ff3-8a31-4737-a970-aeae8fe21765 # Uninstall Security Products
      type: derived
status: test
description: Uninstall an application with wmic
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
author: frack113
date: 2022/01/28
modified: 2023/02/14
tags:
    - attack.execution
    - attack.t1047
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_img:
        - Image|endswith: \WMIC.exe
        - OriginalFileName: wmic.exe
    selection_cli:
        CommandLine|contains:
            - call
            - uninstall
    condition: process_creation and (all of selection_*)
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
