author: Zach Mathis
date: 2022/03/23
modified: 2023/01/13

title: 'Sysmon Config Change'
description: 'This event logs changes in the Sysmon configuration - for example when the filtering rules are updated.'

id: ccd0d7ed-de7d-4948-ab9d-b849cc4a5944
level: informational
status: stable
logsource:
    product: windows
    service: sysmon
    definition: 'Sysmon needs to be installed and configured.'
detection:
    selection_basic:
        Channel: Microsoft-Windows-Sysmon/Operational
        EventID: 16
    condition: selection_basic
falsepositives:
tags:
    - sysmon
references:
    - https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon
ruletype: Hayabusa

sample-evtx: |
    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
        <System>
            <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385F-C22A-43E0-BF4C-06F5698FFBD9}"/>
            <EventID>16</EventID>
            <Version>3</Version>
            <Level>4</Level>
            <Task>16</Task>
            <Opcode>0</Opcode>
            <Keywords>0x8000000000000000</Keywords>
            <TimeCreated SystemTime="2019-04-18T16:55:44.135219200Z"/>
            <EventRecordID>7</EventRecordID>
            <Correlation/>
            <Execution ProcessID="3252" ThreadID="3448"/>
            <Channel>Microsoft-Windows-Sysmon/Operational</Channel>
            <Computer>IEWIN7</Computer>
            <Security UserID="S-1-5-21-3583694148-1414552638-2922671848-1000"/>
        </System>
        <EventData>
            <Data Name="UtcTime">2019-04-18 16:55:44.135</Data>
            <Data Name="Configuration">C:\Users\IEUser\Desktop\sysmonconfig-18-apr-2019.xml</Data>
            <Data Name="ConfigurationFileHash">SHA1=B870A007B7F5FCE50EE1518B7134973327DBAA09</Data>
        </EventData>
    </Event>