title: CVE-2023-40477 Potential Exploitation - WinRAR Application Crash
id: e5a29b54-6fe7-4258-8a23-82960e31231a
status: experimental
description: Detects a crash of "WinRAR.exe" where the version is lower than 6.23. This could indicate potential exploitation of CVE-2023-40477
references:
    - https://wildptr.io/winrar-cve-2023-40477-poc-new-vulnerability-winrar-security-research/
    - https://github.com/wildptr-io/Winrar-CVE-2023-40477-POC
    - https://www.rarlab.com/vuln_rev3_names.html
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/08/31
tags:
    - attack.execution
    - cve.2023.40477
    - detection.emerging_threats
logsource:
    product: windows
    service: application
detection:
    application:
        Channel: Application
    selection:
        Provider_Name: Application Error
        EventID: 1000
        AppName: WinRAR.exe
    filter_main_fixed_version:
        # TODO: fix this when the "lt" modifier is implemented for software versions
        AppVersion|startswith:
            - 6.23.
            - 6.24.
            - 6.25.
            - 6.26.
            - '7.'
    condition: application and (selection and not 1 of filter_main_*)
falsepositives:
    - Legitimate crash for reasons other than exploitation of the vulnerability
level: medium
ruletype: Sigma
