title: Microsoft Malware Protection Engine Crash
ruletype: Sigma
author: Florian Roth (Nextron Systems)
date: 2017/05/09
description: This rule detects a suspicious crash of the Microsoft Malware Protection
    Engine
detection:
    SELECTION_1:
        Channel: Application
    SELECTION_2:
        Provider_Name: Application Error
    SELECTION_3:
        EventID: 1000
    SELECTION_4:
        Data: '*MsMpEng.exe*'
    SELECTION_5:
        Data: '*mpengine.dll*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- MsMpEng might crash if the "C:\" partition is full
id: 545a5da6-f103-4919-a519-e9aec1026ee4
level: high
logsource:
    product: windows
    service: application
modified: 2023/04/14
references:
- https://bugs.chromium.org/p/project-zero/issues/detail?id=1252&desc=5
- https://technet.microsoft.com/en-us/library/security/4022344
related:
-   id: 6c82cf5c-090d-4d57-9188-533577631108
    type: similar
status: experimental
tags:
- attack.defense_evasion
- attack.t1211
- attack.t1562.001

