title: Suspicious AppX Package Locations
ruletype: Sigma
author: Nasreddine Bencherchali
date: 2023/01/11
description: Detects an appx package added the pipeline of the "to be processed" packages
    which is located in suspicious locations
detection:
    SELECTION_1:
        Provider_Name: Microsoft-Windows-AppXDeploymentServer/Operational
    SELECTION_2:
        EventID: 854
    SELECTION_3:
        Path:
        - '*C:\Users\Public\\*'
        - '*/users/public/*'
        - '*C:\PerfLogs\\*'
        - '*C:/perflogs/*'
        - '*\Desktop\\*'
        - '*/desktop/*'
        - '*\Downloads\\*'
        - '*/Downloads/*'
        - '*C:\Windows\Temp\\*'
        - '*C:/Windows/Temp/*'
        - '*\AppdData\Local\Temp\\*'
        - '*/AppdData/Local/Temp/*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3)
falsepositives:
- Unknown
id: 5cdeaf3d-1489-477c-95ab-c318559fc051
level: high
logsource:
    product: windows
    service: appxdeployment-server
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
status: experimental
tags:
- attack.defense_evasion

