title: Suspicious AppX Package Installation Attempt
ruletype: Sigma
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/01/11
description: Detects an appx package installation with the error code "0x80073cff".
    Whihc indicates that the package didn't meet the sgining requirements and could
    be suspicious
detection:
    SELECTION_1:
        Channel: Microsoft-Windows-AppXDeploymentServer/Operational
    SELECTION_2:
        EventID: 401
    SELECTION_3:
        ErrorCode: '0x80073cff'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3)
falsepositives:
- Legitimate AppX packages not signed by MS used part of an enterprise
id: 898d5fc9-fbc3-43de-93ad-38e97237c344
level: medium
logsource:
    product: windows
    service: appxdeployment-server
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
status: experimental
tags:
- attack.defense_evasion

