title: Uncommon AppX Package Locations
id: c977cb50-3dff-4a9f-b873-9290f56132f1
status: test
description: Detects an appx package added the pipeline of the "to be processed" packages which is located in uncommon locations
references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/01/11
tags:
    - attack.defense_evasion
logsource:
    product: windows
    service: appxdeployment-server
detection:
    appxdeployment_server:
        Channel: Microsoft-Windows-AppXDeploymentServer/Operational
    selection:
        EventID: 854
    filter_generic:
        Path|contains:
            # Paths can be written using forward slash if the "file://" protocol is used
            - C:\Program Files\WindowsApps\
            - C:\Program Files (x86)\
            - C:\Windows\SystemApps\
            - C:\Windows\PrintDialog\
            - C:\Windows\ImmersiveControlPanel\
            - x-windowsupdate://
            - file:///C:/Program%20Files   # Also covers 'file:///C:/Program%20Files%20(x86)/'
    filter_specific:
        Path|contains:
            - https://statics.teams.cdn.office.net/
            - microsoft.com   # Example: https://go.microsoft.com/fwlink/?linkid=2160968
    condition: appxdeployment_server and (selection and not 1 of filter_*)
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
