
title: RDP Sensitive Settings Changed
ruletype: Sigma
author: Samir Bousseaden, David ANDRE
date: 2019/04/03
description: Detects changes to RDP terminal service sensitive settings
detection:
  SELECTION_1:
    EventID: 12
  SELECTION_2:
    EventID: 13
  SELECTION_3:
    EventID: 14
  SELECTION_4:
    TargetObject:
    - '*\services\TermService\Parameters\ServiceDll*'
    - '*\Control\Terminal Server\fSingleSessionPerUser*'
    - '*\Control\Terminal Server\fDenyTSConnections*'
    - '*\Policies\Microsoft\Windows NT\Terminal Services\Shadow*'
    - '*\Control\Terminal Server\WinStations\RDP-Tcp\InitialProgram*'
  condition: ((SELECTION_1 or SELECTION_2 or SELECTION_3) and SELECTION_4)
falsepositives:
- unknown
id: 171b67e1-74b4-460e-8d55-b331f3e32d67
level: high
logsource:
  category: registry_event
  product: windows
modified: 2021/12/31
references:
- https://blog.menasec.net/2019/02/threat-hunting-rdp-hijacking-via.html
- https://knowledge.insourcess.com/Supporting_Technologies/Wonderware/Tech_Notes/TN_WW213_How_to_shadow_an_established_RDP_Session_on_Windows_10_Pro
- https://twitter.com/SagieSec/status/1469001618863624194?t=HRf0eA0W1YYzkTSHb-Ky1A&s=03
- http://etutorials.org/Microsoft+Products/microsoft+windows+server+2003+terminal+services/Chapter+6+Registry/Registry+Keys+for+Terminal+Services/
status: test
tags:
- attack.defense_evasion
- attack.t1112
