
title: Change Outlook Security Setting in Registry
ruletype: Sigma
author: frack113
date: 2021/12/28
description: Change outlook email security settings
detection:
  SELECTION_1:
    EventID: 12
  SELECTION_2:
    EventID: 13
  SELECTION_3:
    EventID: 14
  SELECTION_4:
    TargetObject: '*\SOFTWARE\Microsoft\Office\\*'
  SELECTION_5:
    TargetObject: '*\Outlook\Security\\*'
  SELECTION_6:
    EventType: SetValue
  condition: ((SELECTION_1 or SELECTION_2 or SELECTION_3) and SELECTION_4 and SELECTION_5
    and SELECTION_6)
falsepositives:
- Administrative scripts
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
level: medium
logsource:
  category: registry_event
  product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1137/T1137.md
- https://docs.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
status: experimental
tags:
- attack.persistence
- attack.t1137
