title: File Creation Related To RAT Clients
id: 0bf5fd34-1e71-59a3-917b-291c2939b9f7
related:
    - id: 2f3039c8-e8fe-43a9-b5cf-dcd424a2522d
      type: derived
status: experimental
description: |
    File .conf created related to VenomRAT, AsyncRAT and Lummac samples observed in the wild.
references:
    - https://www.virustotal.com/gui/file/c9f9f193409217f73cc976ad078c6f8bf65d3aabcf5fad3e5a47536d47aa6761
    - https://www.virustotal.com/gui/file/e96a0c1bc5f720d7f0a53f72e5bb424163c943c24a437b1065957a79f5872675
author: Joseliyo Sanchez, @Joseliyo_Jstnk
date: 2024-12-19
tags:
    - attack.execution
    - detection.emerging-threats
    - sysmon
logsource:
    category: file_event
    product: windows
detection:
    file_event:
        EventID: 11
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_required:
        TargetFilename|contains: \AppData\Roaming\
    selection_variants:
        TargetFilename|contains:
            - \mydata\
            - \datalogs\
            - \hvnc\
            - \dcrat\
        TargetFilename|endswith:
            - \datalogs.conf
            - \hvnc.conf
            - \dcrat.conf
    condition: file_event and (all of selection_*)
falsepositives:
    - Legitimate software creating a file with the same name
level: high
ruletype: Sigma
