title: Remote Thread Created In Shell Application
id: 2df78783-1b8b-8f54-2c37-e557da6a7a34
related:
    - id: a9d4d3fa-8fc0-41bc-80b1-30b9fda79d6f
      type: derived
status: experimental
description: |
    Detects remote thread creation in command shell applications, such as "Cmd.EXE" and "PowerShell.EXE".
    It is a common technique used by malware, such as IcedID, to inject malicious code and execute it within legitimate processes.
references:
    - https://research.splunk.com/endpoint/10399c1e-f51e-11eb-b920-acde48001122/
    - https://www.binarydefense.com/resources/blog/icedid-gziploader-analysis/
author: Splunk Research Team
date: 2024-07-29
tags:
    - attack.defense-evasion
    - attack.t1055
    - sysmon
logsource:
    product: windows
    category: create_remote_thread
detection:
    create_remote_thread:
        EventID: 8
        Channel: Microsoft-Windows-Sysmon/Operational
    selection:
        TargetImage|endswith:
            - \cmd.exe
            - \powershell.exe
            - \pwsh.exe
    condition: create_remote_thread and selection
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
