title: Change Outlook Security Setting in Registry
ruletype: Sigma
author: frack113
date: 2021/12/28
description: Change outlook email security settings
detection:
    SELECTION_1:
        EventID: 13
    SELECTION_2:
        Channel: Microsoft-Windows-Sysmon/Operational
    SELECTION_3:
        TargetObject: '*\SOFTWARE\Microsoft\Office\\*'
    SELECTION_4:
        TargetObject: '*\Outlook\Security\\*'
    SELECTION_5:
        EventType: SetValue
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- Administrative scripts
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
level: medium
logsource:
    category: registry_set
    product: windows
modified: 2022/03/26
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
- https://docs.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
status: test
tags:
- attack.persistence
- attack.t1137

