title: New Lolbin Process by Office Applications
ruletype: Sigma
author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule), Michael Haag
date: 2021/08/23
description: This rule will monitor any office apps that spins up a new LOLBin process.
    This activity is pretty suspicious and should be investigated.
detection:
    SELECTION_1:
        EventID: 4688
    SELECTION_2:
        Channel: Security
    SELECTION_3:
        NewProcessName:
        - '*\regsvr32.exe'
        - '*\rundll32.exe'
        - '*\msiexec.exe'
        - '*\mshta.exe'
        - '*\verclsid.exe'
        - '*\msdt.exe'
        - '*\control.exe'
    SELECTION_4:
        ParentProcessName:
        - '*\winword.exe'
        - '*\excel.exe'
        - '*\powerpnt.exe'
        - '*\msaccess.exe'
        - '*\mspub.exe'
        - '*\eqnedt32.exe'
        - '*\visio.exe'
        - '*\wordpad.exe'
        - '*\wordview.exe'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4)
falsepositives:
- Unknown
id: 23daeb52-e6eb-493c-8607-c4f0246cb7d8
level: high
logsource:
    category: process_creation
    product: windows
modified: 2022/07/20
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://doublepulsar.com/follina-a-microsoft-office-code-execution-vulnerability-1a47fce5629e
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/02bcbfc2bfb8b4da601bb30de0344ae453aa1afe/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
- https://github.com/splunk/security_content/blob/develop/detections/endpoint/office_spawning_control.yml
status: experimental
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defense_evasion
yml_filename: proc_creation_win_lolbins_by_office_applications.yml
yml_path: rules/windows/process_creation
---

