title: Security Support Provider (SSP) Added to LSA Configuration
id: a2b70475-be0a-993d-b01f-8ecf4bbd7576
related:
    - id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
      type: derived
status: test
description: |
    Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
references:
    - https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
    - https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
author: iwillkeepwatch
date: 2019/01/18
modified: 2022/08/09
tags:
    - attack.persistence
    - attack.t1547.005
    - sysmon
logsource:
    category: registry_event
    product: windows
detection:
    registry_event:
        EventID: 4657
        Channel: Security
    selection:
        ObjectName|endswith:
            - \Control\Lsa\Security Packages
            - \Control\Lsa\OSConfig\Security Packages
    filter_main_msiexec:
        ProcessName:
            - C:\Windows\system32\msiexec.exe
            - C:\Windows\syswow64\MsiExec.exe
    condition: registry_event and (selection and not 1 of filter_main_*)
falsepositives:
    - Unknown
level: high
ruletype: Sigma
