
title: DHCP Server Loaded the CallOut DLL
ruletype: Sigma
author: Dimitrios Slamaris
date: 2017/05/15
description: This rule detects a DHCP server in which a specified Callout DLL (in
  registry) was loaded
detection:
  SELECTION_1:
    EventID: 1033
  SELECTION_2:
    Provider_Name: Microsoft-Windows-DHCP-Server
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: 13fc89a9-971e-4ca6-b9dc-aa53a445bf40
level: critical
logsource:
  product: windows
  service: system
modified: 2021/10/13
references:
- https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
- https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
- https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
status: experimental
tags:
- attack.defense_evasion
- attack.t1574.002
