title: Application Terminated Via Wmic.EXE
id: aed91788-6fab-61d2-104a-3a1ea483f8fd
status: experimental
description: Detects calls to the "terminate" function via wmic in order to kill an application
references:
    - https://cyble.com/blog/lockfile-ransomware-using-proxyshell-attack-to-deploy-ransomware/
    - https://www.bitdefender.com/files/News/CaseStudies/study/377/Bitdefender-Whitepaper-WMI-creat4871-en-EN-GenericUse.pdf
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/09/11
tags:
    - attack.execution
    - attack.t1047
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection_img:
        - NewProcessName|endswith: \WMIC.exe
        - OriginalFileName: wmic.exe
    selection_cli:
        CommandLine|contains|all:
            - call
            - terminate
    condition: process_creation and (all of selection_*)
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
