title: Application Removed Via Wmic.EXE
id: 4f8de5d6-a332-76fb-d759-219688d83254
status: test
description: Detects the removal or uninstallation of an application via "Wmic.EXE".
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
author: frack113
date: 2022/01/28
modified: 2024/07/02
tags:
    - attack.execution
    - attack.t1047
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection_img:
        - NewProcessName|endswith: \WMIC.exe
        - OriginalFileName: wmic.exe
    selection_cli:
        CommandLine|contains|all:
            - call
            - uninstall
    condition: process_creation and (all of selection_*)
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
