title: Application Removed Via Wmic.EXE
ruletype: Sigma
author: frac113
date: 2022/01/28
description: Uninstall an application with wmic
detection:
    SELECTION_1:
        EventID: 4688
    SELECTION_2:
        Channel: Security
    SELECTION_3:
        NewProcessName: '*\WMIC.exe'
    SELECTION_4:
        OriginalFileName: wmic.exe
    SELECTION_5:
        CommandLine:
        - '*call*'
        - '*uninstall*'
    condition: ((SELECTION_1 and SELECTION_2) and (SELECTION_3 or SELECTION_4) and
        SELECTION_5)
falsepositives:
- Unknown
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
level: medium
logsource:
    category: process_creation
    product: windows
modified: 2023/02/14
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
related:
-   id: 847d5ff3-8a31-4737-a970-aeae8fe21765
    type: derived
status: experimental
tags:
- attack.execution
- attack.t1047

