title: Sysmon Configuration Update
ruletype: Sigma
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/03/09
description: Detects updates to Sysmon's configuration. Attackers might update or
    replace the Sysmon configuration with a bare bone one to avoid monitoring without
    shutting down the service completely
detection:
    SELECTION_1:
        EventID: 4688
    SELECTION_2:
        Channel: Security
    SELECTION_3:
        NewProcessName:
        - '*\Sysmon64.exe'
        - '*\Sysmon.exe'
    SELECTION_4:
        Description: System activity monitor
    SELECTION_5:
        CommandLine:
        - '*-c*'
        - '*/c*'
    condition: ((SELECTION_1 and SELECTION_2) and (SELECTION_3 or SELECTION_4) and
        SELECTION_5)
falsepositives:
- Legitimate administrators might use this command to update Sysmon configuration.
id: 87911521-7098-470b-a459-9a57fc80bdfd
level: medium
logsource:
    category: process_creation
    product: windows
references:
- https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
status: test
tags:
- attack.defense_evasion
- attack.t1562.001

