title: Using SettingSyncHost.exe as LOLBin
id: b2ddd389-f676-4ac4-845a-e00781a48e5f
status: test
description: Detects using SettingSyncHost.exe to run hijacked binary
references:
    - https://www.hexacorn.com/blog/2020/02/02/settingsynchost-exe-as-a-lolbin
author: Anton Kutepov, oscd.community
date: 2020/02/05
modified: 2021/11/27
tags:
    - attack.execution
    - attack.defense_evasion
    - attack.t1574.008
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    system_utility:
        NewProcessName|startswith:
            - C:\Windows\System32\
            - C:\Windows\SysWOW64\
    parent_is_settingsynchost:
        ParentCommandLine|contains|all:
            - cmd.exe /c
            - RoamDiag.cmd
            - -outputpath
    condition: process_creation and (not system_utility and parent_is_settingsynchost)
fields:
    - NewProcessName
    - TargetFilename
falsepositives:
    - Unknown
level: high
ruletype: Sigma
