Title: 'Object Access Attempt'
Channel: Security
EventID: 4674
RewriteFieldData:
    AccessMask:
        - '%%1537': 'DELETE'
        - '%%1538': 'READ_CONTROL'
        - '%%1539': 'WRITE_DAC'
        - '%%1540': 'WRITE_OWNER'
        - '%%1541': 'SYNCHRONIZE'
        - '%%1542': 'ACCESS_SYS_SEC'
        - '%%4416': 'READ_DATA'
        - '%%4417': 'WRITE_DATA'
        - '%%4418': 'APPEND_DATA'
        - '%%4419': 'READ_EXTENDED_ATTRIBUTES'
        - '%%4420': 'WRITE_EXTENDED_ATTRIBUTES'
        - '%%4421': 'EXECUTE/TRAVERSE'
        - '%%4422': 'DELETE_CHILD'
        - '%%4423': 'READ_ATTRIBUTES'
        - '%%4424': 'WRITE_ATTRIBUTES'
        - '%%4432': 'QUERY_KEY_VALUE'
        - '%%4433': 'SET_KEY_VALUE'
        - '%%4434': 'CREATE_SUBKEY'
        - '%%4435': 'ENUMERATE_SUBKEYS'
        - '%%4436': 'KEY_CHANGES_NOTIFICATION'
        - '%%4437': 'CREATE_LINK'
        - '%%7184': 'SeImpersonatePrivilege'
        - '%%7185': 'SeCreateGlobalPrivilege'
        - '%%7186': 'SeTrustedCredManAccessPrivilege'
        - '%%7187': 'SeRelabelPrivilege'
        - '%%7188': 'SeIncreaseWorkingSetPrivilege'
        - '%%7189': 'SeTimeZonePrivilege'
        - '%%7190': 'SeCreateSymbolicLinkPrivilege'
        - '%%7191': 'SeDelegateSessionUserImpersonatePrivilege'
        - '%%7192': 'SeManageVolumePrivilege'
HexToDecimal: 'ProcessId'

sample-evtx: |
    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
        <System>
            <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}"/>
            <EventID>4674</EventID>
            <Version>0</Version>
            <Level>0</Level>
            <Task>13056</Task>
            <Opcode>0</Opcode>
            <Keywords>0x8020000000000000</Keywords>
            <TimeCreated SystemTime="2020-09-14T14:48:28.683048400Z"/>
            <EventRecordID>39406</EventRecordID>
            <Correlation/>
            <Execution ProcessID="4" ThreadID="5756"/>
            <Channel>Security</Channel>
            <Computer>Sec504Student</Computer>
            <Security/>
        </System>
        <EventData>
            <Data Name="SubjectUserSid">S-1-5-21-2977773840-2930198165-1551093962-1000</Data>
            <Data Name="SubjectUserName">Sec504</Data>
            <Data Name="SubjectDomainName">SEC504STUDENT</Data>
            <Data Name="SubjectLogonId">0x99e3d</Data>
            <Data Name="ObjectServer">SC Manager</Data>
            <Data Name="ObjectType">SERVICE OBJECT</Data>
            <Data Name="ObjectName">nginx</Data>
            <Data Name="HandleId">0xffff820cb1d95928</Data>
            <Data Name="AccessMask">%%1539</Data>
            <Data Name="PrivilegeList">SeSecurityPrivilege</Data>
            <Data Name="ProcessId">0x21c</Data>
            <Data Name="ProcessName">C:\Windows\System32\services.exe</Data>
        </EventData>
    </Event>